### PR TITLE
Fixing + Fortune Cookie

### PR DESCRIPTION
**Pull request by rocx**
The script had an issue especially with $RANDOM, which is neither POSIX nor in `sh`. Temporarily changed the shebang up to use `bash`. Other than that, a couple of quotes that weren't escaped are now escaped.

There is also a `fortune` cookie as well as some instructions on installing it in the README.

### CODE REVIEW

**Comment by xero** [comment]
thanx rocx. i was mostly just getting things started. should have ran checkbashisms

**Comment by rocx** [comment]
```
 _________ 
< bashism >
 --------- 
\
  \
+----  ----+
|   //\\   |
|  //  \\  |
| //    \\ |
|//      \\|
  \      /
   \    /
    \  /
     \/
```

**Comment by dcat** [comment]
```
_MAX=70
_RANDOM=`(od -D -N4 < /dev/urandom | tr -cd '[:digit:]'  ; echo " % $_MAX") | bc`
```

**Comment by branderxero** [comment]
@dcat updated http://git.io/vCQjG

**Comment by xero** [comment]
@dcat updated http://git.io/vCQjG

**Pull request merged**
